[package]
name = "aoc24"
version = "0.1.0"
rust-version = "1.82"
edition = "2021"

[[bin]]
name = "day1"

[[bin]]
name = "day2"

[[bin]]
name = "day3"

[[bin]]
name = "day4"

[[bin]]
name = "day5"

[[bin]]
name = "day6"

[[bin]]
name = "day7"


[dependencies]
rayon = "1.10.0"
